import { expect, test } from '@playwright/test'

test('details and edit identification round trip preserve answers', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/w40')
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await page.getByRole('button', { name: 'Nemám fotografiu' }).click()
  await page.getByRole('combobox').fill('mac')
  await page.getByRole('option', { name: 'Mačka domáca' }).click()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await expect(page.getByRole('heading', { name: 'Doplňte podrobnosti' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Zobraziť možnosti pomoci' })).toBeDisabled()
  await page.getByRole('checkbox', { name: 'Iné', exact: true }).check()
  await page.getByRole('textbox').fill('Poranená labka')
  await page.locator('input[name=conscious][value=yes]').check()
  await page.locator('input[name=juvenile][value=no]').check()
  await page.getByRole('button', { name: 'Zobraziť možnosti pomoci' }).click()
  await expect(page.getByRole('heading', { name: 'Pozor!', exact: true })).toBeVisible()
  await expect(page.locator('.customer-advice__blocks section')).toHaveCount(2)
  await expect(page.locator('.customer-advice__avoid')).toHaveCSS('border-top-color', 'rgb(198, 46, 62)')
  await expect(page.locator('.customer-advice__do')).toHaveCSS('background-color', 'rgb(251, 253, 247)')
  await expect(page.locator('.customer-advice__avoid use')).toHaveAttribute('href', '#icon-attention')
  await expect(page.locator('.customer-advice__do use')).toHaveAttribute('href', '#icon-info')
  await page.screenshot({ path: testInfo.outputPath('advice-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Rozumiem', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('ďalší postup ešte nie sú zapojené')
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('details-mobile.png'), fullPage: true })
  await page.getByRole('button', { name: 'Upraviť', exact: true }).click()
  await page.getByRole('combobox').fill('morca')
  await page.getByRole('combobox').press('ArrowDown')
  await page.getByRole('combobox').press('Enter')
  await expect(page.getByText('Morča domáce', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox')).toHaveValue('Poranená labka')
  await page.getByRole('button', { name: 'Upraviť', exact: true }).click()
  await page.getByRole('button', { name: 'Prejsť na manuálny výber zvieraťa' }).click()
  await page.getByRole('radio', { name: 'Neviem identifikovať', exact: true }).check()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await expect(page.getByText('Neidentifikované zviera', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.screenshot({ path: testInfo.outputPath('details-desktop.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(1280)
})
