import { expect, test } from '@playwright/test'

test('replaces many cards with fewer sequentially without collapsing the area', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await page.getByRole('button', { name: 'Nemám fotografiu' }).click()
  await expect(page.locator('.customer-animal-groups__grid')).toBeVisible()
  await page.getByRole('button', { name: 'Domáce zvieratá', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Mačky', exact: true })).toBeVisible()
  await expect(page.locator('.customer-animal-groups__grid')).toHaveCount(1)
  const oldHeight = (await page.locator('.customer-animal-groups__cards').boundingBox())!.height
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const frames = await page.evaluate(async () => {
    document.querySelector<HTMLButtonElement>('.customer-animal-groups__grid button')!.click()
    await new Promise<void>(resolve =>
      requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(() => resolve())))
    )
    return Array.from(document.querySelectorAll<HTMLElement>('.customer-animal-groups__grid')).map(grid => {
      const animations = grid.getAnimations()
      for (const animation of animations) {
        animation.pause()
        animation.currentTime = 60
      }
      return {
        transform: getComputedStyle(grid).transform,
        opacity: Number(getComputedStyle(grid).opacity),
        count: animations.length
      }
    })
  })
  expect(frames).toHaveLength(1)
  for (const frame of frames) {
    expect(frame.transform).toBe('none')
    expect(frame.count).toBe(1)
    expect(frame.opacity).toBeGreaterThan(0)
    expect(frame.opacity).toBeLessThan(1)
  }
  expect((await page.locator('.customer-animal-groups__cards').boundingBox())!.height).toBeCloseTo(oldHeight, 0)
  await expect(page.getByRole('button', { name: 'Mačka domáca', exact: true })).toHaveCount(0)
  await page.evaluate(() =>
    document
      .querySelectorAll('.customer-animal-groups__grid')
      .forEach(grid => grid.getAnimations().forEach(animation => animation.finish()))
  )
  await expect(page.locator('.customer-animal-groups__grid')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Mačka domáca', exact: true })).toBeVisible()
  await expect(page.locator('.customer-animal-groups__grid')).toHaveCSS('opacity', '1')
  await expect(page.locator('.customer-animal-groups__cards')).not.toHaveAttribute('style', /height:/)
  expect((await page.locator('.customer-animal-groups__cards').boundingBox())!.height).toBeLessThan(oldHeight)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: 'Začať výber odznova' }).click()
  await expect(page.getByRole('button', { name: 'Domáce zvieratá', exact: true })).toBeVisible()
  await expect(page.locator('.customer-animal-groups__grid')).toHaveCount(1)
  expect(await page.locator('.customer-animal-groups__grid').evaluate(grid => grid.getAnimations().length)).toBe(0)
})

test('opens the manual group fixture, selects a group and preserves it on return', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/w06')
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await page.getByRole('button', { name: 'Nemám fotografiu' }).click()
  await expect(page.getByRole('heading', { name: 'O aké zviera ide?' })).toBeVisible()
  await expect(page.locator('.customer-animal-groups__grid button')).toHaveCount(2)
  const footer = page.locator('.customer-animal-groups__actions')
  const initialFooterTop = (await footer.boundingBox())!.y
  const search = page.getByRole('combobox', { name: 'Vyhľadať zviera' })
  await expect(search).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('manual-groups-mobile.png'), fullPage: true })
  const grid = page.locator('.customer-animal-groups__grid')
  const gridBefore = await grid.boundingBox()
  await search.fill('mac')
  await expect(page.getByRole('option')).toHaveCount(1)
  await expect(page.getByRole('option', { name: 'Mačka domáca', exact: true })).toContainText('Domáce zvieratá')
  expect((await grid.boundingBox())?.y).toBe(gridBefore?.y)
  await page.screenshot({ path: testInfo.outputPath('manual-search-overlay.png'), fullPage: true })
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(search).toHaveValue('')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Mačka domáca', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await search.fill('pes dom')
  await expect(page.getByRole('option')).toHaveCount(1)
  await page.getByRole('option', { name: 'Pes domáci', exact: true }).click()
  await expect(search).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Pes domáci', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await search.fill('morca')
  await page.getByRole('option', { name: 'Morča domáce', exact: true }).click()
  await expect(grid.locator('button').first()).toHaveText('Morča domáce')
  await expect(grid.locator('button').first()).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Škrečok zlatý', exact: true }).click()
  await expect(grid.locator('button').first()).toHaveText('Morča domáce')
  await search.fill('xyz')
  await expect(page.getByRole('listbox')).toContainText('V ukážkovom číselníku sa nenašla zhoda.')
  await search.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await search.fill('mac')
  await expect(page.getByRole('option')).toHaveCount(1)
  await search.press('Tab')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await page.getByRole('button', { name: 'Začať výber odznova' }).click()
  const birds = page.getByRole('button', { name: 'Hospodárske zvieratá', exact: true })
  await birds.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'O aké zviera ide?' })).toBeVisible()
  await page.getByRole('button', { name: 'Hydina', exact: true }).click()
  expect((await footer.boundingBox())!.y).toBeCloseTo(initialFooterTop, 0)
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeDisabled()
  await page.getByRole('radio', { name: 'Iný druh hydiny' }).check()
  await expect(search).toBeVisible()
  await expect(grid).toBeVisible()
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: 'Popis zvieraťa' })).toHaveCSS('resize', 'none')
  await expect(page.getByRole('textbox', { name: 'Popis zvieraťa' })).toHaveAttribute('placeholder', 'Popis zvieraťa')
  await page.getByRole('textbox', { name: 'Popis zvieraťa' }).fill('   ')
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeDisabled()
  await page.getByRole('textbox', { name: 'Popis zvieraťa' }).fill('Malá hydina')
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('manual-species-other.png'), fullPage: true })
  await expect(page.getByRole('button', { name: 'Neviem identifikovať' })).toHaveCount(0)
  await page.getByRole('radio', { name: 'Neviem identifikovať' }).check()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await expect(page.getByRole('heading', { name: 'Doplňte podrobnosti' })).toBeVisible()
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Popis zvieraťa' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Sliepka domáca', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Neviem identifikovať' })).not.toBeChecked()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await expect(page.getByRole('heading', { name: 'Doplňte podrobnosti' })).toBeVisible()
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await page.getByRole('button', { name: 'Začať výber odznova' }).click()
  await page.getByRole('button', { name: 'Hospodárske zvieratá', exact: true }).click()
  await search.fill('mac')
  await expect(page.getByRole('option')).toHaveCount(1)
  await search.press('Escape')
  await page.getByRole('button', { name: 'Mláďa', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Teľa', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeDisabled()
  await page.getByRole('radio', { name: 'Neviem identifikovať' }).check()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await expect(page.getByRole('heading', { name: 'Doplňte podrobnosti' })).toBeVisible()
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Pridajte fotografiu alebo video' })).toBeVisible()
  await page.getByRole('button', { name: 'Nemám fotografiu' }).click()
  await page.getByRole('button', { name: 'Začať výber odznova' }).click()
  await expect(birds).toBeVisible()
  await page.setViewportSize({ width: 1280, height: 800 })
  await expect(grid).toHaveCount(1)
  const animationArea = await page.locator('.customer-animal-groups__cards').boundingBox()
  expect(animationArea!.x).toBe(320)
  expect(animationArea!.width).toBe(640)
  expect((await grid.boundingBox())!.width).toBe(640)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(1280)
  await page.screenshot({ path: testInfo.outputPath('manual-groups-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.getByRole('button', { name: 'Domáce zvieratá', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Akváriové zvieratá', exact: true })).toBeVisible()
  await expect(page.locator('.customer-animal-groups__cards')).not.toHaveAttribute('style', /height:/)
  await expect(grid).toHaveCount(1)
  const searchTop = (await search.boundingBox())!.y
  const gridTop = (await grid.boundingBox())!.y
  await page.evaluate(() => window.scrollTo(0, 200))
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBeGreaterThan(0)
  expect((await search.boundingBox())!.y).toBeLessThan(searchTop)
  await expect(page.locator('.customer-animal-groups__top')).toHaveCSS('position', 'static')
  await expect(page.locator('.customer-animal-groups__top')).toHaveCSS('box-shadow', 'none')
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeVisible()
  await page.getByRole('button', { name: 'Akváriové zvieratá', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ryby', exact: true })).toBeVisible()
  await expect(grid).toHaveCount(1)
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(0)
  expect((await grid.boundingBox())!.y).toBe(gridTop)
  await page.getByRole('button', { name: 'Ryby', exact: true }).click()
  await page.getByRole('button', { name: 'Sladkovodné ryby', exact: true }).click()
  await page.getByRole('button', { name: 'Gupka dúhová', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Začať výber odznova' })).toBeVisible()
  await page.getByRole('button', { name: 'Začať výber odznova' }).click()
  await expect(page.locator('.customer-animal-groups__grid button')).toHaveCount(2)
  await expect(search).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Začať výber odznova' })).toBeDisabled()
  await search.fill('ma')
  await expect(page.getByRole('button', { name: 'Začať výber odznova' })).toBeEnabled()
  await page.getByRole('button', { name: 'Začať výber odznova' }).click()
  await expect(search).toHaveValue('')
  await expect(page.getByRole('button', { name: 'Začať výber odznova' })).toBeDisabled()
  await page.reload()
  await expect(page).toHaveURL(/\/$/)
})
