import { expect, test, type Page } from '@playwright/test'

async function leave(page: Page) {
  await page.getByRole('button', { name: 'Opustiť hlásenie prípadu', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Opustiť hlásenie prípadu' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Opustiť hlásenie prípadu', exact: true }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.locator('.customer-home__draft')).toBeVisible()
}

test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/?fixture=clean')
})

test('cancel, Escape, save and resume an unconfirmed location; close the saved case', async ({ page }, testInfo) => {
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  const trigger = page.getByRole('button', { name: 'Opustiť hlásenie prípadu', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog')
  const stay = dialog.getByRole('button', { name: 'Pokračovať v hlásení prípadu' })
  await expect(stay).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Opustiť hlásenie prípadu', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(stay).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('exit-mobile.png') })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.screenshot({ path: testInfo.outputPath('exit-desktop.png') })
  await stay.click()
  await expect(trigger).toBeFocused()
  await expect(page).toHaveURL(/\/w03$/)
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await leave(page)
  await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
  await expect(page).toHaveURL(/\/w03$/)
  await expect(page.getByRole('button', { name: 'Potvrdiť polohu' })).toBeEnabled()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await expect(page).toHaveURL(/\/w04$/)
  await leave(page)
  await expect(page.locator('.customer-home__draft')).toContainText('Dolné Orešany')
  await page.getByRole('button', { name: 'Uzavrieť prípad', exact: true }).click()
  await expect(page.locator('.customer-home__draft')).toHaveCount(0)
  await page.goBack()
  await expect(page).toHaveURL(/\/$/)
})

test('resumes a nested manual selection and then partially completed details', async ({ page }) => {
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await page.getByRole('button', { name: 'Nemám fotografiu' }).click()
  await page.getByRole('combobox').fill('mac')
  await page.getByRole('option', { name: 'Mačka domáca' }).click()
  await leave(page)
  await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
  await expect(page).toHaveURL(/\/w06$/)
  await expect(page.getByRole('button', { name: 'Potvrdiť voľbu' })).toBeEnabled()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await page.getByRole('checkbox', { name: 'Iné', exact: true }).check()
  await page.getByRole('textbox').fill('Poranená labka')
  await leave(page)
  await expect(page.locator('.customer-home__draft')).toContainText('Mačka domáca')
  await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
  await expect(page).toHaveURL(/\/w09$/)
  await expect(page.getByRole('checkbox', { name: 'Iné', exact: true })).toBeChecked()
  await expect(page.getByRole('textbox')).toHaveValue('Poranená labka')
})

for (const [choice, route] of [
  ['Zviera je zatúlané', 'w03'],
  ['Nález mŕtveho zvieraťa', 'w03'],
  ['Týranie/zanedbávanie zvieraťa', 'w27'],
  ['Iné', 'w32']
] as const) {
  test(`can leave and resume the ${choice} branch`, async ({ page }) => {
    await page.getByRole('button', { name: choice, exact: true }).click()
    await leave(page)
    await expect(page.locator('.customer-home__draft')).toContainText(choice!)
    await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
    await expect(page).toHaveURL(new RegExp(`/${route}$`))
  })
}

test('retains uploaded media and the unfinished final form when leaving', async ({ page }) => {
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await page.locator('input[type=file]').first().setInputFiles('src/assets/demo/macka.png')
  await leave(page)
  await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
  await expect(page).toHaveURL(/\/w04$/)
  await expect(page.locator('img[src^="blob:"]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Odstrániť súbor: macka.png', exact: true }).click()
  await page.getByRole('button', { name: 'Nemám fotografiu' }).click()
  await page.getByRole('combobox').fill('mac')
  await page.getByRole('option', { name: 'Mačka domáca' }).click()
  await page.getByRole('button', { name: 'Potvrdiť voľbu' }).click()
  await page.getByRole('checkbox', { name: 'Iné', exact: true }).check()
  await page.getByRole('textbox').fill('Poranená labka')
  await page.locator('input[name=conscious][value=yes]').check()
  await page.locator('input[name=juvenile][value=no]').check()
  await page.getByRole('button', { name: 'Zobraziť možnosti pomoci' }).click()
  await page.getByRole('button', { name: 'Rozumiem', exact: true }).click()
  await page.getByRole('button', { name: 'Podarilo sa pomôcť', exact: true }).click()
  const email = page.getByRole('textbox', { name: 'E-mail (nepovinné)' })
  await email.fill('draft@example.org')
  await page.getByRole('checkbox').first().check()
  const finalUrl = page.url()
  await leave(page)
  await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
  await expect(page).toHaveURL(finalUrl)
  await expect(email).toHaveValue('draft@example.org')
  await expect(page.getByRole('checkbox').first()).toBeChecked()
})
