import { expect, test } from '@playwright/test'

test('previews the draft card without changing a real case', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/?fixture=draft')
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '35')
  await expect(page.getByText('Dolné Orešany')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('home-draft.png'), fullPage: true })
  await page.getByRole('button', { name: 'Pokračovať', exact: true }).click()
  await expect(page).toHaveURL(/\/w03$/)
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await expect(page).toHaveURL(/fixture=draft/)
  await page.getByRole('button', { name: 'Uzavrieť prípad', exact: true }).click()
  await expect(page.getByRole('progressbar')).toHaveCount(0)
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  await page.goto('/?fixture=clean')
  await expect(page.getByRole('progressbar')).toHaveCount(0)
})

test('homepage showcase renders data-driven footer sections and draft by default', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/')
  await expect(page.getByRole('progressbar')).toBeVisible()
  await expect(page.getByText('Zverolinka o.z.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Prejsť na všetky FAQs', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Ukážkový režim')
  await page.getByRole('button', { name: 'Právne informácie', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ochrana osobných údajov' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('home-footer.png'), fullPage: true })
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
})
