import { expect, test } from '@playwright/test'

test('animates screen content without moving the header', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  await expect(page.getByRole('status', { name: 'Vitajte v Zverolinke' })).toHaveCount(0)
  const header = await page.locator('.customer-app__header').boundingBox()
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  const location = page.locator('.customer-location')
  await expect(location).toBeVisible()
  await expect(location).not.toHaveClass(/screen-enter-active/)
  await expect(location).toHaveCSS('opacity', '1')
  await expect(location).toHaveCSS('transform', 'none')
  expect(await page.locator('.customer-app__header').boundingBox()).toEqual(header)
  await page.getByRole('button', { name: 'Späť', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Čo sa stalo?' })).toBeVisible()
})

test('guards direct entry and previews location selection without submitting', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/w03')
  await expect(page).toHaveURL(/\/$/)
  const homeHeader = await page.locator('.customer-app__header').boundingBox()
  const homeTitle = await page.locator('.customer-home__intro h1').boundingBox()
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  await expect(page).toHaveURL(/\/w03$/)
  expect(await page.locator('.customer-app__header').boundingBox()).toEqual(homeHeader)
  const back = await page.locator('.customer-location__back button').boundingBox()
  expect(homeTitle!.y + homeTitle!.height / 2).toBeCloseTo(back!.y + back!.height / 2, 1)
  await expect(page.locator('.customer-location__selector')).toHaveCSS('border-top-left-radius', '0px')
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(page.locator('.customer-location__selector')).toHaveCSS('border-top-left-radius', '16px')
  await page.setViewportSize({ width: 402, height: 874 })
  await expect(page.getByRole('button', { name: 'Otvoriť menu' })).toHaveCount(0)
  await expect(page.locator('.customer-home__footer')).toHaveCount(0)
  const confirm = page.getByRole('button', { name: 'Potvrdiť polohu' })
  await expect(confirm).toBeDisabled()
  const mapBounds = await page.locator('.customer-location__map').boundingBox()
  await page.getByRole('combobox').fill('oresany')
  await expect(page.getByRole('listbox')).toBeVisible()
  expect(await page.locator('.customer-location__map').boundingBox()).toEqual(mapBounds)
  await expect(page.getByRole('combobox')).toHaveCSS('outline-style', 'none')
  await page.getByRole('option', { name: 'Dolné Orešany', exact: true }).click()
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await expect(confirm).toBeEnabled()
  await confirm.click()
  await expect(page.getByText('Poloha potvrdená iba v ukážke.', { exact: false })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('location.png'), fullPage: true })
  await page.getByRole('combobox').fill('neexistuje')
  await expect(confirm).toBeDisabled()
  await expect(page.getByText('V ukážkových dátach sa nenašla zhoda.')).toBeVisible()
  await page.reload()
  await expect(page).toHaveURL(/\/$/)
})

test('supports keyboard selection and dismissing the location overlay', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Zviera je zranené', exact: true }).click()
  const input = page.getByRole('combobox')
  await input.fill('a')
  await input.press('ArrowDown')
  await expect(page.getByRole('option').first()).toHaveAttribute('aria-selected', 'true')
  await input.press('Escape')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(page.getByRole('button', { name: 'Potvrdiť polohu' })).toBeEnabled()
  await input.fill('trn')
  await input.press('Tab')
  await expect(page.getByRole('listbox')).toHaveCount(0)
})

test('uses device location only on request and handles denial', async ({ page, context }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await context.grantPermissions(['geolocation'])
  await context.setGeolocation({ latitude: 48.15, longitude: 17.11 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Zviera je zatúlané', exact: true }).click()
  await page.getByRole('button', { name: 'Použiť moju polohu' }).click()
  await expect(page.getByText('Moja poloha (48.15000, 17.11000)', { exact: false })).toBeVisible()
  await page.evaluate(() => {
    Object.defineProperty(navigator.geolocation, 'getCurrentPosition', {
      configurable: true,
      value: (_success: unknown, fail: (error: { code: number }) => void) => fail({ code: 1 })
    })
  })
  await page.getByRole('button', { name: 'Použiť moju polohu' }).click()
  await expect(page.getByText('Prístup k polohe nebol povolený.', { exact: false })).toBeVisible()
})
