import { expect, test } from '@playwright/test'

test('shows the branded splash then the home shell', async ({ page }) => {
  await page.clock.install()
  await page.clock.pauseAt(new Date())
  await page.goto('/')
  const splash = page.getByRole('status', { name: 'Vitajte v Zverolinke' })
  await expect(splash).toBeVisible()
  await expect(splash.getByRole('img', { name: 'Zverolinka' })).toBeVisible()
  await page.clock.runFor(1700)
  await expect(splash).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Čo sa stalo?' })).toBeVisible()
})

test('fills desktop width, centers content and keeps mobile overflow-free', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Otvoriť menu' })).toBeVisible()
  const shell = page.locator('.customer-app')
  await expect(shell).toHaveCSS('width', '1280px')
  const content = page.getByRole('main')
  await expect(content).toHaveCSS('width', '640px')
  await expect(page.locator('.customer-home__about header')).toHaveCSS('border-top-left-radius', '16px')
  await expect(page.locator('.customer-home__sections')).toHaveCSS('border-bottom-left-radius', '16px')
  const box = await content.boundingBox()
  expect(box?.x).toBe(320)
  await page.setViewportSize({ width: 641, height: 800 })
  await expect(page.locator('.customer-home__about header')).toHaveCSS('border-top-left-radius', '16px')
  await page.setViewportSize({ width: 640, height: 800 })
  await expect(page.locator('.customer-home__about header')).toHaveCSS('border-top-left-radius', '0px')
  await page.setViewportSize({ width: 1280, height: 800 })
  await page.getByRole('button', { name: 'Otvoriť menu' }).click()
  const drawer = page.locator('.customer-app__drawer')
  expect((await drawer.boundingBox())?.x).toBe(0)
  await expect(drawer).toHaveCSS('width', '324px')
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 320, height: 568 })
  await expect(shell).toHaveCSS('width', '320px')
  await expect(page.locator('.customer-home__about header')).toHaveCSS('border-top-left-radius', '0px')
  await expect(page.locator('.customer-home__sections')).toHaveCSS('border-bottom-left-radius', '0px')
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(320)
  await expect(page.locator("symbol[id^='icon-']")).toHaveCount(57)
  await expect(page.getByText('Hlásenie ešte nie je možné odoslať.', { exact: false })).toHaveCount(0)
})

test('opens an accessible drawer, traps focus and restores the trigger', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Otvoriť menu' })
  const headerLogo = await page.locator('.customer-app__header img').boundingBox()
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Hlavné menu' })
  await expect(dialog).toBeVisible()
  const drawerLogo = await dialog.getByRole('img', { name: 'Zverolinka' }).boundingBox()
  expect(drawerLogo).toEqual(headerLogo)
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(dialog.getByRole('button', { name: 'Zatvoriť menu' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'TikTok' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Zatvoriť menu' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await trigger.click()
  await dialog.click({ position: { x: 390, y: 200 } })
  await expect(dialog).toBeHidden()
})

test('supports direct routes and honest unfinished menu actions', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/missing')
  await expect(page.getByRole('heading', { name: 'Stránka sa nenašla' })).toBeVisible()
  await expect(page.locator('.customer-home__footer')).toHaveCount(0)
  await page.getByRole('button', { name: 'Otvoriť menu' }).click()
  await page.getByRole('link', { name: 'Domov', exact: true }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('heading', { name: 'Čo sa stalo?' })).toBeVisible()
  await page.getByRole('button', { name: 'Otvoriť menu' }).click()
  await expect(page.getByRole('button', { name: 'Časté otázky a návody' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Staň sa dobrovoľníkom' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Podpor Zverolinku' })).toBeDisabled()
  await page.getByRole('link', { name: 'Moje prípady' }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('dialog')).toBeHidden()
})

test('keeps drawer navigation scrollable on short screens', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 402, height: 874 })
  await page.goto('/')
  await expect(page.getByRole('status', { name: 'Vitajte v Zverolinke' })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('shell.png'), fullPage: true })
  await page.getByRole('button', { name: 'Otvoriť menu' }).click()
  await page.screenshot({ path: testInfo.outputPath('drawer.png') })
  await page.setViewportSize({ width: 320, height: 320 })
  const dialog = page.getByRole('dialog')
  await dialog.getByRole('button', { name: 'Podpor Zverolinku' }).scrollIntoViewIfNeeded()
  await expect(dialog.getByRole('button', { name: 'Podpor Zverolinku' })).toBeInViewport()
  await dialog.getByRole('button', { name: 'Zatvoriť menu' }).click()
  await expect(dialog).toBeHidden()
})
