import { expect, test } from '@playwright/test'

test('validation preview retains the draft and allows correction', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByRole('button', { name: 'Iné', exact: true }).click()
  await page.getByRole('button', { name: 'Na/pri ceste alebo koľajniciach' }).click()
  await page.getByRole('button', { name: 'Ukážková mapa — vybrať Dolné Orešany' }).click()
  await page.getByRole('button', { name: 'Potvrdiť polohu' }).click()
  await page.getByRole('radio', { name: 'Pohybuje sa na alebo pri diaľnici', exact: true }).check()
  await page.getByRole('button', { name: 'Zobraziť možnosti pomoci' }).click()
  await page.getByRole('button', { name: 'Podarilo sa pomôcť', exact: true }).click()
  const email = page.locator('input[type=email]')
  await expect(email).toHaveValue('nespravna-adresa')
  await expect(email).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByText('Zadajte platnú e-mailovú adresu, napríklad meno@example.sk.')).toBeVisible()
  await page.screenshot({ path: '/tmp/customer-validation-preview.png', fullPage: true })
  await page.locator('input[name=name]').fill('Testovacie meno')
  await email.fill('user@example.org')
  await expect(email).not.toHaveAttribute('aria-invalid')
  await expect(page.locator('input[name=name]')).toHaveValue('Testovacie meno')
  await page.getByRole('button', { name: 'Odoslať a ukončiť' }).click()
  await expect(page).toHaveURL('/')
})
